### PR TITLE
Update DotNetSortRefs.csproj with net7 & 8

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by mysticmind** [comment]
Thanks @jchannon, will do a release during my day tomorrow.

**Comment by jchannon** [comment]
Great stuff! Thanks @mysticmind =)

**Comment by mysticmind** [comment]
v2.0.0 is published to NuGet.

**Comment by jchannon** [comment]
Thanks @mysticmind, much appreciated!

**Pull request merged**
